
UPDATE DEMO_USER SET KARMAPOINTS = 1700, CATEGORY_ID = 1 WHERE FIRSTNAME = 'Milton';
UPDATE DEMO_USER SET KARMAPOINTS = 2300, CATEGORY_ID = 3 WHERE FIRSTNAME = 'Evan';
UPDATE DEMO_USER SET KARMAPOINTS = 500, CATEGORY_ID = 3 WHERE FIRSTNAME = 'Gurudatt';
UPDATE DEMO_USER SET KARMAPOINTS = 3700, CATEGORY_ID = 2 WHERE FIRSTNAME = 'Antonia';
UPDATE DEMO_USER SET KARMAPOINTS = 1200, CATEGORY_ID = 4 WHERE FIRSTNAME = 'Christoph';
UPDATE DEMO_USER SET KARMAPOINTS = 800, CATEGORY_ID = 4 WHERE FIRSTNAME = 'Jean';
UPDATE DEMO_USER SET KARMAPOINTS = 700, CATEGORY_ID = 4 WHERE FIRSTNAME = 'Sundeep';
UPDATE DEMO_USER SET KARMAPOINTS = 900, CATEGORY_ID = 5 WHERE FIRSTNAME = 'Harish';
UPDATE DEMO_USER SET KARMAPOINTS = 600, CATEGORY_ID = 1 WHERE FIRSTNAME = 'Rachel';
UPDATE DEMO_USER SET KARMAPOINTS = 200, CATEGORY_ID = 1 WHERE FIRSTNAME = 'Mike';


SELECT * FROM DEMO_ACTIVITY;

DELETE FROM DEMO_ACTIVITY;

SELECT * FROM DEMO_OPPORTUNITY WHERE STARTDATE < '2020-09-02';
UPDATE DEMO_OPPORTUNITY SET STATE = 'pending' WHERE STARTDATE > '2020-09-01';
UPDATE DEMO_OPPORTUNITY SET STATE = 'completed' WHERE STARTDATE < '2020-09-02';