export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const FACEBOOK_RESPONSE = "FACEBOOK_RESPONSE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const SET_MESSAGE = "SET_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const SET_OPPORTUNITIES = "GET_OPPORTUNITIES";
export const SET_OPPORTUNITIES_FAILED = "GET_OPPORTUNITIES_FAILED";
