export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const FACEBOOK_RESPONSE = "FACEBOOK_RESPONSE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

export const SET_MESSAGE = "SET_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const SET_OPPORTUNITIES = "SET_OPPORTUNITIES";
export const UPDATE_OPPORTUNITY = "UPDATE_OPPORTUNITY";
export const SET_OPPORTUNITIES_FAILED = "SET_OPPORTUNITIES_FAILED";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_FAILED = "SET_PRODUCTS_FAILED";
export const SET_MY_PRODUCTS = "SET_MY_PRODUCTS";
export const SET_MY_PRODUCTS_FAILED = "SET_MY_PRODUCTS_FAILED";

export const SET_SERVICES = "SET_SERVICES";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const SET_SERVICES_FAILED = "SET_SERVICES_FAILED";
export const SET_MY_SERVICES = "SET_MY_SERVICES";
export const SET_MY_SERVICES_FAILED = "SET_MY_SERVICES_FAILED";

export const SET_TOP_MATCHES = "SET_TOP_MATCHES";
export const SET_TOP_MATCHES_FAILED = "SET_TOP_MATCHES_FAILED";
